name: Generate Keystore

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate Keystore
      run: |
        keytool -genkey -v \
          -keystore my-notes-keystore.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias my-notes-key \
          -storepass MyNotesApp2024! \
          -keypass MyNotesApp2024! \
          -dname "CN=My Notes App, OU=Development, O=Whymyhuman, L=Jakarta, ST=Jakarta, C=ID"

    - name: Convert keystore to base64
      run: |
        base64 -w 0 my-notes-keystore.jks > keystore-base64.txt
        echo "Keystore generated and converted to base64"
        echo "File size: $(wc -c < keystore-base64.txt) characters"

    - name: Upload keystore as artifact
      uses: actions/upload-artifact@v4
      with:
        name: keystore-base64
        path: keystore-base64.txt
        retention-days: 1

    - name: Show instructions
      run: |
        echo "=================================================="
        echo "KEYSTORE GENERATED SUCCESSFULLY!"
        echo "=================================================="
        echo ""
        echo "Next steps:"
        echo "1. Download the 'keystore-base64' artifact from this workflow run"
        echo "2. Copy the content of keystore-base64.txt"
        echo "3. Add it as a GitHub secret named 'KEYSTORE_BASE64'"
        echo ""
        echo "The following secrets are already configured:"
        echo "- KEYSTORE_PASSWORD: MyNotesApp2024!"
        echo "- KEY_ALIAS: my-notes-key"
        echo "- KEY_PASSWORD: MyNotesApp2024!"
        echo ""
        echo "After adding KEYSTORE_BASE64 secret, your app will be signed automatically!"
        echo "=================================================="